language: java
sudo: false

jdk:
  - oraclejdk8
script: mvn clean verify

notifications:
  email:
    recipients:
      - holysz.monika@gmail.com
      - andrzej.kimel@gmail.com
    on_success: change
    on_failure: always

deploy:
  provider: heroku
  app: $HEROKU_APP_NAME
  api_key: $HEROKU_API_KEY